# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hain.proto\"\x0e\n\x0cProbeRequest\"\x1d\n\rProbeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t21\n\x05\x43hain\x12(\n\x05Probe\x12\r.ProbeRequest\x1a\x0e.ProbeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROBEREQUEST._serialized_start=15
  _PROBEREQUEST._serialized_end=29
  _PROBERESPONSE._serialized_start=31
  _PROBERESPONSE._serialized_end=60
  _CHAIN._serialized_start=62
  _CHAIN._serialized_end=111
# @@protoc_insertion_point(module_scope)
