# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hain.proto\"\x0e\n\x0cProbeRequest\"\x1d\n\rProbeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x10\n\x0eProcessRequest\"$\n\x0fProcessResponse\x12\x11\n\tprocesses\x18\x01 \x03(\t\"\x0f\n\rChainResponse\"!\n\x0c\x43hainRequest\x12\x11\n\tprocesses\x18\x01 \x03(\t2\x90\x01\n\x05\x43hain\x12(\n\x05Probe\x12\r.ProbeRequest\x1a\x0e.ProbeResponse\"\x00\x12\x30\n\tProcesses\x12\x0f.ProcessRequest\x1a\x10.ProcessResponse\"\x00\x12+\n\x08SetChain\x12\r.ChainRequest\x1a\x0e.ChainResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROBEREQUEST._serialized_start=15
  _PROBEREQUEST._serialized_end=29
  _PROBERESPONSE._serialized_start=31
  _PROBERESPONSE._serialized_end=60
  _PROCESSREQUEST._serialized_start=62
  _PROCESSREQUEST._serialized_end=78
  _PROCESSRESPONSE._serialized_start=80
  _PROCESSRESPONSE._serialized_end=116
  _CHAINRESPONSE._serialized_start=118
  _CHAINRESPONSE._serialized_end=133
  _CHAINREQUEST._serialized_start=135
  _CHAINREQUEST._serialized_end=168
  _CHAIN._serialized_start=171
  _CHAIN._serialized_end=315
# @@protoc_insertion_point(module_scope)
