# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain_replication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63hain_replication.proto\"\x0c\n\nAckRequest\"\'\n\x0b\x41\x63kResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\x0e\n\x0cStartMessage\"\x1e\n\rStartResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32`\n\x10\x43hainReplication\x12\"\n\x03\x41\x63k\x12\x0b.AckRequest\x1a\x0c.AckResponse\"\x00\x12(\n\x05Start\x12\r.StartMessage\x1a\x0e.StartResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chain_replication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACKREQUEST._serialized_start=27
  _ACKREQUEST._serialized_end=39
  _ACKRESPONSE._serialized_start=41
  _ACKRESPONSE._serialized_end=80
  _STARTMESSAGE._serialized_start=82
  _STARTMESSAGE._serialized_end=96
  _STARTRESPONSE._serialized_start=98
  _STARTRESPONSE._serialized_end=128
  _CHAINREPLICATION._serialized_start=130
  _CHAINREPLICATION._serialized_end=226
# @@protoc_insertion_point(module_scope)
